In [1]:
import pandas as pd
import numpy as np
import csv
import math
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../origin_data/ETH.csv')
df

,frame_id,agent_id,pos_x,pos_y,vel_x,vel_y,scene_id,label,timestamp
0,780,1,8.456844,3.588066,1.671714,0.176292,0,pedestrian,52.0
1,786,1,9.125530,3.658583,1.662877,0.326723,0,pedestrian,52.4
2,792,1,9.787146,3.849445,1.683334,0.371084,0,pedestrian,52.8
3,798,1,10.472197,3.955450,1.598568,0.264795,0,pedestrian,53.2
4,804,1,11.066000,4.061280,1.574526,0.456390,0,pedestrian,53.6
...,...,...,...,...,...,...,...,...,...
8903,12381,357,10.449366,6.229233,0.596406,0.066591,0,pedestrian,825.4
8904,12381,367,11.201661,8.443910,0.000000,0.000000,0,pedestrian,825.4
8905,12381,366,12.132311,6.984982,0.733247,-0.531564,0,pedestrian,825.4
8906,12381,364,12.369087,4.146375,1.139005,0.166531,0,pedestrian,825.4
8907,12381,365,12.708071,5.336541,0.922475,-0.233965,0,pedestrian,825.4

In [4]:
FIRST=True
sample=[]
sample_cnt=0
target=[]
save_folder = '../split_data/'
file_name = 0
split_frame_num = 6

for i in range(len(df)):
  lst = df.iloc[i]
  new_frame = lst[0]
  ped_id = int(lst[1])

  if FIRST:
    frame = new_frame
    FIRST=False
    sample.append(lst)
    continue
  else:
    pass

  # next sample  
  if frame != new_frame:
    sample_cnt += 1
    frame = new_frame
    
    #reset
    while sample_cnt==split_frame_num:
      file_name += 1

      others_data = sample
      # target_data = target
      sample = []
      # target = []
      sample_cnt = 0
      df_others = pd.DataFrame(others_data)
      df_others.columns = ['frame_id', 'agent_id', 'pos_x', 'pos_y', 'vel_x', 'vel_y', 'scene_id', 'label', 'timestamp']
      # df_target = pd.DataFrame(target_data)
      # df_target.columns = ['frame_id', 'agent_id', 'pos_x', 'pos_y', 'vel_x', 'vel_y', 'scene_id', 'label', 'timestamp']
      # print(df_target)
      with open(save_folder+ '{0:03}'.format(file_name)+'.csv', mode= 'a') as f:
        df_others.to_csv(f, header = True, index = False)
      FIRST = True
      continue

    sample.append(lst)

  else:
    sample.append(lst)